### ISSUE TITLE
property types for php unioun types not supported?

### ISSUE THREAD

**Issue by emreakay** [spatie/data-transfer-object#154] opened 2020-12-14 20:54 UTC
```php
final class ProductDTO extends DataTransferObject
{
    public int | string $id;
}
```

```php
$productDTO = new ProductDTO(
    ['id' => $item->id]
 );
```

is not working.

**Comment by mfn** [comment] 2020-12-15 15:48
Duplicate of https://github.com/spatie/data-transfer-object/issues/153 , see the answer there please.

**Closed** 2020-12-17 05:10 UTC

**Comment by emreakay** [comment] 2020-12-17 14:54
thanks
